packages:
  - apps/*
  - packages/*

catalog:
  better-auth: 1.3.27
  hono: ^4.11.3
  '@trpc/server': ^11.8.1
  dotenv: ^17.2.3
  zod: 4.1.12
  typescript: ^5.9.3
  '@types/node': ^25.0.3
  tsdown: ^0.18.3
  '@trpc/client': ^11.8.1
  drizzle-orm: ^0.45.1
  '@tanstack/react-table': ^8.21.3
  '@types/pg': ^8.16.0
