packages:
  - apps/*
  - packages/*

minimumReleaseAge: 0

catalogMode: prefer

catalog:
  "@hono/trpc-server": 0.4.2
  "@mantine/charts": 9.5.2
  "@mantine/core": 9.5.2
  "@mantine/dates": 9.5.2
  "@mantine/form": 9.5.2
  "@mantine/hooks": 9.5.2
  "@mantine/modals": 9.5.2
  "@mantine/notifications": 9.5.2
  "@mantine/schedule": 9.5.2
  "@trpc/client": 11.18.0
  "@trpc/server": 11.18.0
  "@trpc/tanstack-react-query": 11.18.0
  "@types/node": 26.2.0
  "@types/react": 19.2.18
  "@types/react-dom": 19.2.4
  better-auth: 1.7.1
  hono: 4.13.2
  react: 19.2.8
  react-dom: 19.2.8
  tsx: 4.23.11
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  zod: 4.4.3

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
