packages:
  - apps/*
  - packages/*

catalog:
  better-auth: 1.3.27
  hono: ^4.10.8
  '@trpc/server': ^11.7.2
  dotenv: ^17.2.3
  zod: 4.1.12
  typescript: ^5.9.3
  '@types/node': ^22.19.2
  tsdown: ^0.15.12
  '@trpc/client': ^11.7.2
  drizzle-orm: ^0.44.7
  '@tanstack/react-table': ^8.21.3
  '@types/pg': ^8.15.6
