/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedHairSalesRouteRouteImport } from './routes/_authenticated/hair-sales/route'
import { Route as AuthenticatedHairOrdersRouteRouteImport } from './routes/_authenticated/hair-orders/route'
import { Route as AuthenticatedDocumentsRouteRouteImport } from './routes/_authenticated/documents/route'
import { Route as AuthenticatedCustomersRouteRouteImport } from './routes/_authenticated/customers/route'
import { Route as AuthenticatedAppointmentsRouteRouteImport } from './routes/_authenticated/appointments/route'
import { Route as AuthenticatedSalonsIndexRouteImport } from './routes/_authenticated/salons/index'
import { Route as AuthenticatedLegalEntitiesIndexRouteImport } from './routes/_authenticated/legal-entities/index'
import { Route as AuthenticatedHairSalesIndexRouteImport } from './routes/_authenticated/hair-sales/index'
import { Route as AuthenticatedHairOrdersIndexRouteImport } from './routes/_authenticated/hair-orders/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedSalonsSalonIdRouteImport } from './routes/_authenticated/salons/$salonId'
import { Route as AuthenticatedHairSalesHairSaleIdRouteImport } from './routes/_authenticated/hair-sales/$hairSaleId'
import { Route as AuthenticatedHairOrdersHairOrderIdRouteImport } from './routes/_authenticated/hair-orders/$hairOrderId'
import { Route as AuthenticatedAppointmentsAppointmentIdRouteImport } from './routes/_authenticated/appointments/$appointmentId'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdRouteRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/route'
import { Route as AuthenticatedCustomersCustomerIdRouteRouteImport } from './routes/_authenticated/customers/$customerId/route'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdIndexRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/index'
import { Route as AuthenticatedCustomersCustomerIdIndexRouteImport } from './routes/_authenticated/customers/$customerId/index'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdSalonsRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/salons'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdReportsRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/reports'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdOverviewRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/overview'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdDocumentsRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/documents'
import { Route as AuthenticatedDocumentsDocumentIdMatchRouteImport } from './routes/_authenticated/documents/$documentId/match'
import { Route as AuthenticatedCustomersCustomerIdNotesRouteImport } from './routes/_authenticated/customers/$customerId/notes'
import { Route as AuthenticatedCustomersCustomerIdHairSalesRouteImport } from './routes/_authenticated/customers/$customerId/hair-sales'
import { Route as AuthenticatedCustomersCustomerIdAppointmentsRouteImport } from './routes/_authenticated/customers/$customerId/appointments'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/bank-accounts/index'
import { Route as AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRouteImport } from './routes/_authenticated/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHairSalesRouteRoute =
  AuthenticatedHairSalesRouteRouteImport.update({
    id: '/hair-sales',
    path: '/hair-sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHairOrdersRouteRoute =
  AuthenticatedHairOrdersRouteRouteImport.update({
    id: '/hair-orders',
    path: '/hair-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRouteRoute =
  AuthenticatedDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRouteRoute =
  AuthenticatedCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsRouteRoute =
  AuthenticatedAppointmentsRouteRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalonsIndexRoute =
  AuthenticatedSalonsIndexRouteImport.update({
    id: '/salons/',
    path: '/salons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesIndexRoute =
  AuthenticatedLegalEntitiesIndexRouteImport.update({
    id: '/legal-entities/',
    path: '/legal-entities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHairSalesIndexRoute =
  AuthenticatedHairSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHairSalesRouteRoute,
  } as any)
const AuthenticatedHairOrdersIndexRoute =
  AuthenticatedHairOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHairOrdersRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentsRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersRouteRoute,
  } as any)
const AuthenticatedSalonsSalonIdRoute =
  AuthenticatedSalonsSalonIdRouteImport.update({
    id: '/salons/$salonId',
    path: '/salons/$salonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHairSalesHairSaleIdRoute =
  AuthenticatedHairSalesHairSaleIdRouteImport.update({
    id: '/$hairSaleId',
    path: '/$hairSaleId',
    getParentRoute: () => AuthenticatedHairSalesRouteRoute,
  } as any)
const AuthenticatedHairOrdersHairOrderIdRoute =
  AuthenticatedHairOrdersHairOrderIdRouteImport.update({
    id: '/$hairOrderId',
    path: '/$hairOrderId',
    getParentRoute: () => AuthenticatedHairOrdersRouteRoute,
  } as any)
const AuthenticatedAppointmentsAppointmentIdRoute =
  AuthenticatedAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdRouteRoute =
  AuthenticatedLegalEntitiesLegalEntityIdRouteRouteImport.update({
    id: '/legal-entities/$legalEntityId',
    path: '/legal-entities/$legalEntityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRouteRoute =
  AuthenticatedCustomersCustomerIdRouteRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdIndexRoute =
  AuthenticatedLegalEntitiesLegalEntityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdIndexRoute =
  AuthenticatedCustomersCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersCustomerIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute =
  AuthenticatedLegalEntitiesLegalEntityIdSalonsRouteImport.update({
    id: '/salons',
    path: '/salons',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdReportsRoute =
  AuthenticatedLegalEntitiesLegalEntityIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute =
  AuthenticatedLegalEntitiesLegalEntityIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute =
  AuthenticatedLegalEntitiesLegalEntityIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdMatchRoute =
  AuthenticatedDocumentsDocumentIdMatchRouteImport.update({
    id: '/$documentId/match',
    path: '/$documentId/match',
    getParentRoute: () => AuthenticatedDocumentsRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdNotesRoute =
  AuthenticatedCustomersCustomerIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedCustomersCustomerIdRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdHairSalesRoute =
  AuthenticatedCustomersCustomerIdHairSalesRouteImport.update({
    id: '/hair-sales',
    path: '/hair-sales',
    getParentRoute: () => AuthenticatedCustomersCustomerIdRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdAppointmentsRoute =
  AuthenticatedCustomersCustomerIdAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedCustomersCustomerIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute =
  AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
  } as any)
const AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute =
  AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRouteImport.update(
    {
      id: '/bank-accounts/$bankAccountId',
      path: '/bank-accounts/$bankAccountId',
      getParentRoute: () => AuthenticatedLegalEntitiesLegalEntityIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRouteRouteWithChildren
  '/hair-orders': typeof AuthenticatedHairOrdersRouteRouteWithChildren
  '/hair-sales': typeof AuthenticatedHairSalesRouteRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRouteRouteWithChildren
  '/legal-entities/$legalEntityId': typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRouteWithChildren
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/hair-orders/$hairOrderId': typeof AuthenticatedHairOrdersHairOrderIdRoute
  '/hair-sales/$hairSaleId': typeof AuthenticatedHairSalesHairSaleIdRoute
  '/salons/$salonId': typeof AuthenticatedSalonsSalonIdRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/hair-orders/': typeof AuthenticatedHairOrdersIndexRoute
  '/hair-sales/': typeof AuthenticatedHairSalesIndexRoute
  '/legal-entities/': typeof AuthenticatedLegalEntitiesIndexRoute
  '/salons/': typeof AuthenticatedSalonsIndexRoute
  '/customers/$customerId/appointments': typeof AuthenticatedCustomersCustomerIdAppointmentsRoute
  '/customers/$customerId/hair-sales': typeof AuthenticatedCustomersCustomerIdHairSalesRoute
  '/customers/$customerId/notes': typeof AuthenticatedCustomersCustomerIdNotesRoute
  '/documents/$documentId/match': typeof AuthenticatedDocumentsDocumentIdMatchRoute
  '/legal-entities/$legalEntityId/documents': typeof AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute
  '/legal-entities/$legalEntityId/overview': typeof AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute
  '/legal-entities/$legalEntityId/reports': typeof AuthenticatedLegalEntitiesLegalEntityIdReportsRoute
  '/legal-entities/$legalEntityId/salons': typeof AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute
  '/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/legal-entities/$legalEntityId/': typeof AuthenticatedLegalEntitiesLegalEntityIdIndexRoute
  '/legal-entities/$legalEntityId/bank-accounts/$bankAccountId': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute
  '/legal-entities/$legalEntityId/bank-accounts/': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/hair-orders/$hairOrderId': typeof AuthenticatedHairOrdersHairOrderIdRoute
  '/hair-sales/$hairSaleId': typeof AuthenticatedHairSalesHairSaleIdRoute
  '/salons/$salonId': typeof AuthenticatedSalonsSalonIdRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/hair-orders': typeof AuthenticatedHairOrdersIndexRoute
  '/hair-sales': typeof AuthenticatedHairSalesIndexRoute
  '/legal-entities': typeof AuthenticatedLegalEntitiesIndexRoute
  '/salons': typeof AuthenticatedSalonsIndexRoute
  '/customers/$customerId/appointments': typeof AuthenticatedCustomersCustomerIdAppointmentsRoute
  '/customers/$customerId/hair-sales': typeof AuthenticatedCustomersCustomerIdHairSalesRoute
  '/customers/$customerId/notes': typeof AuthenticatedCustomersCustomerIdNotesRoute
  '/documents/$documentId/match': typeof AuthenticatedDocumentsDocumentIdMatchRoute
  '/legal-entities/$legalEntityId/documents': typeof AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute
  '/legal-entities/$legalEntityId/overview': typeof AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute
  '/legal-entities/$legalEntityId/reports': typeof AuthenticatedLegalEntitiesLegalEntityIdReportsRoute
  '/legal-entities/$legalEntityId/salons': typeof AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/legal-entities/$legalEntityId': typeof AuthenticatedLegalEntitiesLegalEntityIdIndexRoute
  '/legal-entities/$legalEntityId/bank-accounts/$bankAccountId': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute
  '/legal-entities/$legalEntityId/bank-accounts': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRouteRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteRouteWithChildren
  '/_authenticated/hair-orders': typeof AuthenticatedHairOrdersRouteRouteWithChildren
  '/_authenticated/hair-sales': typeof AuthenticatedHairSalesRouteRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRouteRouteWithChildren
  '/_authenticated/legal-entities/$legalEntityId': typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRouteWithChildren
  '/_authenticated/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/_authenticated/hair-orders/$hairOrderId': typeof AuthenticatedHairOrdersHairOrderIdRoute
  '/_authenticated/hair-sales/$hairSaleId': typeof AuthenticatedHairSalesHairSaleIdRoute
  '/_authenticated/salons/$salonId': typeof AuthenticatedSalonsSalonIdRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/hair-orders/': typeof AuthenticatedHairOrdersIndexRoute
  '/_authenticated/hair-sales/': typeof AuthenticatedHairSalesIndexRoute
  '/_authenticated/legal-entities/': typeof AuthenticatedLegalEntitiesIndexRoute
  '/_authenticated/salons/': typeof AuthenticatedSalonsIndexRoute
  '/_authenticated/customers/$customerId/appointments': typeof AuthenticatedCustomersCustomerIdAppointmentsRoute
  '/_authenticated/customers/$customerId/hair-sales': typeof AuthenticatedCustomersCustomerIdHairSalesRoute
  '/_authenticated/customers/$customerId/notes': typeof AuthenticatedCustomersCustomerIdNotesRoute
  '/_authenticated/documents/$documentId/match': typeof AuthenticatedDocumentsDocumentIdMatchRoute
  '/_authenticated/legal-entities/$legalEntityId/documents': typeof AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute
  '/_authenticated/legal-entities/$legalEntityId/overview': typeof AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute
  '/_authenticated/legal-entities/$legalEntityId/reports': typeof AuthenticatedLegalEntitiesLegalEntityIdReportsRoute
  '/_authenticated/legal-entities/$legalEntityId/salons': typeof AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute
  '/_authenticated/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/_authenticated/legal-entities/$legalEntityId/': typeof AuthenticatedLegalEntitiesLegalEntityIdIndexRoute
  '/_authenticated/legal-entities/$legalEntityId/bank-accounts/$bankAccountId': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute
  '/_authenticated/legal-entities/$legalEntityId/bank-accounts/': typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/appointments'
    | '/customers'
    | '/documents'
    | '/hair-orders'
    | '/hair-sales'
    | '/calendar'
    | '/cash'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$customerId'
    | '/legal-entities/$legalEntityId'
    | '/appointments/$appointmentId'
    | '/hair-orders/$hairOrderId'
    | '/hair-sales/$hairSaleId'
    | '/salons/$salonId'
    | '/customers/'
    | '/documents/'
    | '/hair-orders/'
    | '/hair-sales/'
    | '/legal-entities/'
    | '/salons/'
    | '/customers/$customerId/appointments'
    | '/customers/$customerId/hair-sales'
    | '/customers/$customerId/notes'
    | '/documents/$documentId/match'
    | '/legal-entities/$legalEntityId/documents'
    | '/legal-entities/$legalEntityId/overview'
    | '/legal-entities/$legalEntityId/reports'
    | '/legal-entities/$legalEntityId/salons'
    | '/customers/$customerId/'
    | '/legal-entities/$legalEntityId/'
    | '/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'
    | '/legal-entities/$legalEntityId/bank-accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/cash'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/appointments/$appointmentId'
    | '/hair-orders/$hairOrderId'
    | '/hair-sales/$hairSaleId'
    | '/salons/$salonId'
    | '/customers'
    | '/documents'
    | '/hair-orders'
    | '/hair-sales'
    | '/legal-entities'
    | '/salons'
    | '/customers/$customerId/appointments'
    | '/customers/$customerId/hair-sales'
    | '/customers/$customerId/notes'
    | '/documents/$documentId/match'
    | '/legal-entities/$legalEntityId/documents'
    | '/legal-entities/$legalEntityId/overview'
    | '/legal-entities/$legalEntityId/reports'
    | '/legal-entities/$legalEntityId/salons'
    | '/customers/$customerId'
    | '/legal-entities/$legalEntityId'
    | '/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'
    | '/legal-entities/$legalEntityId/bank-accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/appointments'
    | '/_authenticated/customers'
    | '/_authenticated/documents'
    | '/_authenticated/hair-orders'
    | '/_authenticated/hair-sales'
    | '/_authenticated/calendar'
    | '/_authenticated/cash'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/legal-entities/$legalEntityId'
    | '/_authenticated/appointments/$appointmentId'
    | '/_authenticated/hair-orders/$hairOrderId'
    | '/_authenticated/hair-sales/$hairSaleId'
    | '/_authenticated/salons/$salonId'
    | '/_authenticated/customers/'
    | '/_authenticated/documents/'
    | '/_authenticated/hair-orders/'
    | '/_authenticated/hair-sales/'
    | '/_authenticated/legal-entities/'
    | '/_authenticated/salons/'
    | '/_authenticated/customers/$customerId/appointments'
    | '/_authenticated/customers/$customerId/hair-sales'
    | '/_authenticated/customers/$customerId/notes'
    | '/_authenticated/documents/$documentId/match'
    | '/_authenticated/legal-entities/$legalEntityId/documents'
    | '/_authenticated/legal-entities/$legalEntityId/overview'
    | '/_authenticated/legal-entities/$legalEntityId/reports'
    | '/_authenticated/legal-entities/$legalEntityId/salons'
    | '/_authenticated/customers/$customerId/'
    | '/_authenticated/legal-entities/$legalEntityId/'
    | '/_authenticated/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'
    | '/_authenticated/legal-entities/$legalEntityId/bank-accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hair-sales': {
      id: '/_authenticated/hair-sales'
      path: '/hair-sales'
      fullPath: '/hair-sales'
      preLoaderRoute: typeof AuthenticatedHairSalesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hair-orders': {
      id: '/_authenticated/hair-orders'
      path: '/hair-orders'
      fullPath: '/hair-orders'
      preLoaderRoute: typeof AuthenticatedHairOrdersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salons/': {
      id: '/_authenticated/salons/'
      path: '/salons'
      fullPath: '/salons/'
      preLoaderRoute: typeof AuthenticatedSalonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal-entities/': {
      id: '/_authenticated/legal-entities/'
      path: '/legal-entities'
      fullPath: '/legal-entities/'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hair-sales/': {
      id: '/_authenticated/hair-sales/'
      path: '/'
      fullPath: '/hair-sales/'
      preLoaderRoute: typeof AuthenticatedHairSalesIndexRouteImport
      parentRoute: typeof AuthenticatedHairSalesRouteRoute
    }
    '/_authenticated/hair-orders/': {
      id: '/_authenticated/hair-orders/'
      path: '/'
      fullPath: '/hair-orders/'
      preLoaderRoute: typeof AuthenticatedHairOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedHairOrdersRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentsRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersRouteRoute
    }
    '/_authenticated/salons/$salonId': {
      id: '/_authenticated/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/salons/$salonId'
      preLoaderRoute: typeof AuthenticatedSalonsSalonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hair-sales/$hairSaleId': {
      id: '/_authenticated/hair-sales/$hairSaleId'
      path: '/$hairSaleId'
      fullPath: '/hair-sales/$hairSaleId'
      preLoaderRoute: typeof AuthenticatedHairSalesHairSaleIdRouteImport
      parentRoute: typeof AuthenticatedHairSalesRouteRoute
    }
    '/_authenticated/hair-orders/$hairOrderId': {
      id: '/_authenticated/hair-orders/$hairOrderId'
      path: '/$hairOrderId'
      fullPath: '/hair-orders/$hairOrderId'
      preLoaderRoute: typeof AuthenticatedHairOrdersHairOrderIdRouteImport
      parentRoute: typeof AuthenticatedHairOrdersRouteRoute
    }
    '/_authenticated/appointments/$appointmentId': {
      id: '/_authenticated/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AuthenticatedAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId': {
      id: '/_authenticated/legal-entities/$legalEntityId'
      path: '/legal-entities/$legalEntityId'
      fullPath: '/legal-entities/$legalEntityId'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteRouteImport
      parentRoute: typeof AuthenticatedCustomersRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/': {
      id: '/_authenticated/legal-entities/$legalEntityId/'
      path: '/'
      fullPath: '/legal-entities/$legalEntityId/'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdIndexRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/customers/$customerId/': {
      id: '/_authenticated/customers/$customerId/'
      path: '/'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersCustomerIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/salons': {
      id: '/_authenticated/legal-entities/$legalEntityId/salons'
      path: '/salons'
      fullPath: '/legal-entities/$legalEntityId/salons'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdSalonsRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/reports': {
      id: '/_authenticated/legal-entities/$legalEntityId/reports'
      path: '/reports'
      fullPath: '/legal-entities/$legalEntityId/reports'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdReportsRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/overview': {
      id: '/_authenticated/legal-entities/$legalEntityId/overview'
      path: '/overview'
      fullPath: '/legal-entities/$legalEntityId/overview'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdOverviewRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/documents': {
      id: '/_authenticated/legal-entities/$legalEntityId/documents'
      path: '/documents'
      fullPath: '/legal-entities/$legalEntityId/documents'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/documents/$documentId/match': {
      id: '/_authenticated/documents/$documentId/match'
      path: '/$documentId/match'
      fullPath: '/documents/$documentId/match'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdMatchRouteImport
      parentRoute: typeof AuthenticatedDocumentsRouteRoute
    }
    '/_authenticated/customers/$customerId/notes': {
      id: '/_authenticated/customers/$customerId/notes'
      path: '/notes'
      fullPath: '/customers/$customerId/notes'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdNotesRouteImport
      parentRoute: typeof AuthenticatedCustomersCustomerIdRouteRoute
    }
    '/_authenticated/customers/$customerId/hair-sales': {
      id: '/_authenticated/customers/$customerId/hair-sales'
      path: '/hair-sales'
      fullPath: '/customers/$customerId/hair-sales'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdHairSalesRouteImport
      parentRoute: typeof AuthenticatedCustomersCustomerIdRouteRoute
    }
    '/_authenticated/customers/$customerId/appointments': {
      id: '/_authenticated/customers/$customerId/appointments'
      path: '/appointments'
      fullPath: '/customers/$customerId/appointments'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdAppointmentsRouteImport
      parentRoute: typeof AuthenticatedCustomersCustomerIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/bank-accounts/': {
      id: '/_authenticated/legal-entities/$legalEntityId/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/legal-entities/$legalEntityId/bank-accounts/'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
    '/_authenticated/legal-entities/$legalEntityId/bank-accounts/$bankAccountId': {
      id: '/_authenticated/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'
      path: '/bank-accounts/$bankAccountId'
      fullPath: '/legal-entities/$legalEntityId/bank-accounts/$bankAccountId'
      preLoaderRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRouteImport
      parentRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRoute
    }
  }
}

interface AuthenticatedAppointmentsRouteRouteChildren {
  AuthenticatedAppointmentsAppointmentIdRoute: typeof AuthenticatedAppointmentsAppointmentIdRoute
}

const AuthenticatedAppointmentsRouteRouteChildren: AuthenticatedAppointmentsRouteRouteChildren =
  {
    AuthenticatedAppointmentsAppointmentIdRoute:
      AuthenticatedAppointmentsAppointmentIdRoute,
  }

const AuthenticatedAppointmentsRouteRouteWithChildren =
  AuthenticatedAppointmentsRouteRoute._addFileChildren(
    AuthenticatedAppointmentsRouteRouteChildren,
  )

interface AuthenticatedCustomersCustomerIdRouteRouteChildren {
  AuthenticatedCustomersCustomerIdAppointmentsRoute: typeof AuthenticatedCustomersCustomerIdAppointmentsRoute
  AuthenticatedCustomersCustomerIdHairSalesRoute: typeof AuthenticatedCustomersCustomerIdHairSalesRoute
  AuthenticatedCustomersCustomerIdNotesRoute: typeof AuthenticatedCustomersCustomerIdNotesRoute
  AuthenticatedCustomersCustomerIdIndexRoute: typeof AuthenticatedCustomersCustomerIdIndexRoute
}

const AuthenticatedCustomersCustomerIdRouteRouteChildren: AuthenticatedCustomersCustomerIdRouteRouteChildren =
  {
    AuthenticatedCustomersCustomerIdAppointmentsRoute:
      AuthenticatedCustomersCustomerIdAppointmentsRoute,
    AuthenticatedCustomersCustomerIdHairSalesRoute:
      AuthenticatedCustomersCustomerIdHairSalesRoute,
    AuthenticatedCustomersCustomerIdNotesRoute:
      AuthenticatedCustomersCustomerIdNotesRoute,
    AuthenticatedCustomersCustomerIdIndexRoute:
      AuthenticatedCustomersCustomerIdIndexRoute,
  }

const AuthenticatedCustomersCustomerIdRouteRouteWithChildren =
  AuthenticatedCustomersCustomerIdRouteRoute._addFileChildren(
    AuthenticatedCustomersCustomerIdRouteRouteChildren,
  )

interface AuthenticatedCustomersRouteRouteChildren {
  AuthenticatedCustomersCustomerIdRouteRoute: typeof AuthenticatedCustomersCustomerIdRouteRouteWithChildren
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedCustomersRouteRouteChildren: AuthenticatedCustomersRouteRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRouteRoute:
      AuthenticatedCustomersCustomerIdRouteRouteWithChildren,
    AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  }

const AuthenticatedCustomersRouteRouteWithChildren =
  AuthenticatedCustomersRouteRoute._addFileChildren(
    AuthenticatedCustomersRouteRouteChildren,
  )

interface AuthenticatedDocumentsRouteRouteChildren {
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedDocumentsDocumentIdMatchRoute: typeof AuthenticatedDocumentsDocumentIdMatchRoute
}

const AuthenticatedDocumentsRouteRouteChildren: AuthenticatedDocumentsRouteRouteChildren =
  {
    AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
    AuthenticatedDocumentsDocumentIdMatchRoute:
      AuthenticatedDocumentsDocumentIdMatchRoute,
  }

const AuthenticatedDocumentsRouteRouteWithChildren =
  AuthenticatedDocumentsRouteRoute._addFileChildren(
    AuthenticatedDocumentsRouteRouteChildren,
  )

interface AuthenticatedHairOrdersRouteRouteChildren {
  AuthenticatedHairOrdersHairOrderIdRoute: typeof AuthenticatedHairOrdersHairOrderIdRoute
  AuthenticatedHairOrdersIndexRoute: typeof AuthenticatedHairOrdersIndexRoute
}

const AuthenticatedHairOrdersRouteRouteChildren: AuthenticatedHairOrdersRouteRouteChildren =
  {
    AuthenticatedHairOrdersHairOrderIdRoute:
      AuthenticatedHairOrdersHairOrderIdRoute,
    AuthenticatedHairOrdersIndexRoute: AuthenticatedHairOrdersIndexRoute,
  }

const AuthenticatedHairOrdersRouteRouteWithChildren =
  AuthenticatedHairOrdersRouteRoute._addFileChildren(
    AuthenticatedHairOrdersRouteRouteChildren,
  )

interface AuthenticatedHairSalesRouteRouteChildren {
  AuthenticatedHairSalesHairSaleIdRoute: typeof AuthenticatedHairSalesHairSaleIdRoute
  AuthenticatedHairSalesIndexRoute: typeof AuthenticatedHairSalesIndexRoute
}

const AuthenticatedHairSalesRouteRouteChildren: AuthenticatedHairSalesRouteRouteChildren =
  {
    AuthenticatedHairSalesHairSaleIdRoute:
      AuthenticatedHairSalesHairSaleIdRoute,
    AuthenticatedHairSalesIndexRoute: AuthenticatedHairSalesIndexRoute,
  }

const AuthenticatedHairSalesRouteRouteWithChildren =
  AuthenticatedHairSalesRouteRoute._addFileChildren(
    AuthenticatedHairSalesRouteRouteChildren,
  )

interface AuthenticatedLegalEntitiesLegalEntityIdRouteRouteChildren {
  AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute
  AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute
  AuthenticatedLegalEntitiesLegalEntityIdReportsRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdReportsRoute
  AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute
  AuthenticatedLegalEntitiesLegalEntityIdIndexRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdIndexRoute
  AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute
  AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute
}

const AuthenticatedLegalEntitiesLegalEntityIdRouteRouteChildren: AuthenticatedLegalEntitiesLegalEntityIdRouteRouteChildren =
  {
    AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute:
      AuthenticatedLegalEntitiesLegalEntityIdDocumentsRoute,
    AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute:
      AuthenticatedLegalEntitiesLegalEntityIdOverviewRoute,
    AuthenticatedLegalEntitiesLegalEntityIdReportsRoute:
      AuthenticatedLegalEntitiesLegalEntityIdReportsRoute,
    AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute:
      AuthenticatedLegalEntitiesLegalEntityIdSalonsRoute,
    AuthenticatedLegalEntitiesLegalEntityIdIndexRoute:
      AuthenticatedLegalEntitiesLegalEntityIdIndexRoute,
    AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute:
      AuthenticatedLegalEntitiesLegalEntityIdBankAccountsBankAccountIdRoute,
    AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute:
      AuthenticatedLegalEntitiesLegalEntityIdBankAccountsIndexRoute,
  }

const AuthenticatedLegalEntitiesLegalEntityIdRouteRouteWithChildren =
  AuthenticatedLegalEntitiesLegalEntityIdRouteRoute._addFileChildren(
    AuthenticatedLegalEntitiesLegalEntityIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRouteRoute: typeof AuthenticatedAppointmentsRouteRouteWithChildren
  AuthenticatedCustomersRouteRoute: typeof AuthenticatedCustomersRouteRouteWithChildren
  AuthenticatedDocumentsRouteRoute: typeof AuthenticatedDocumentsRouteRouteWithChildren
  AuthenticatedHairOrdersRouteRoute: typeof AuthenticatedHairOrdersRouteRouteWithChildren
  AuthenticatedHairSalesRouteRoute: typeof AuthenticatedHairSalesRouteRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLegalEntitiesLegalEntityIdRouteRoute: typeof AuthenticatedLegalEntitiesLegalEntityIdRouteRouteWithChildren
  AuthenticatedSalonsSalonIdRoute: typeof AuthenticatedSalonsSalonIdRoute
  AuthenticatedLegalEntitiesIndexRoute: typeof AuthenticatedLegalEntitiesIndexRoute
  AuthenticatedSalonsIndexRoute: typeof AuthenticatedSalonsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRouteRoute:
    AuthenticatedAppointmentsRouteRouteWithChildren,
  AuthenticatedCustomersRouteRoute:
    AuthenticatedCustomersRouteRouteWithChildren,
  AuthenticatedDocumentsRouteRoute:
    AuthenticatedDocumentsRouteRouteWithChildren,
  AuthenticatedHairOrdersRouteRoute:
    AuthenticatedHairOrdersRouteRouteWithChildren,
  AuthenticatedHairSalesRouteRoute:
    AuthenticatedHairSalesRouteRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLegalEntitiesLegalEntityIdRouteRoute:
    AuthenticatedLegalEntitiesLegalEntityIdRouteRouteWithChildren,
  AuthenticatedSalonsSalonIdRoute: AuthenticatedSalonsSalonIdRoute,
  AuthenticatedLegalEntitiesIndexRoute: AuthenticatedLegalEntitiesIndexRoute,
  AuthenticatedSalonsIndexRoute: AuthenticatedSalonsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
