/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardCustomersIndexRouteImport } from './routes/_authenticated/dashboard/customers/index'
import { Route as AuthenticatedDashboardCustomersIdRouteImport } from './routes/_authenticated/dashboard/customers/$id'
import { Route as AuthenticatedDashboardCustomersIdIndexRouteImport } from './routes/_authenticated/dashboard/customers/$id/index'
import { Route as AuthenticatedDashboardCustomersIdHistoryRouteImport } from './routes/_authenticated/dashboard/customers/$id/history'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCustomersIndexRoute =
  AuthenticatedDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCustomersIdRoute =
  AuthenticatedDashboardCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCustomersIdIndexRoute =
  AuthenticatedDashboardCustomersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardCustomersIdRoute,
  } as any)
const AuthenticatedDashboardCustomersIdHistoryRoute =
  AuthenticatedDashboardCustomersIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardCustomersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdRouteWithChildren
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersIndexRoute
  '/dashboard/customers/$id/history': typeof AuthenticatedDashboardCustomersIdHistoryRoute
  '/dashboard/customers/$id/': typeof AuthenticatedDashboardCustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersIndexRoute
  '/dashboard/customers/$id/history': typeof AuthenticatedDashboardCustomersIdHistoryRoute
  '/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdRouteWithChildren
  '/_authenticated/dashboard/customers/': typeof AuthenticatedDashboardCustomersIndexRoute
  '/_authenticated/dashboard/customers/$id/history': typeof AuthenticatedDashboardCustomersIdHistoryRoute
  '/_authenticated/dashboard/customers/$id/': typeof AuthenticatedDashboardCustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/customers/$id'
    | '/dashboard/customers'
    | '/dashboard/customers/$id/history'
    | '/dashboard/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/customers/$id/history'
    | '/dashboard/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/customers/$id'
    | '/_authenticated/dashboard/customers/'
    | '/_authenticated/dashboard/customers/$id/history'
    | '/_authenticated/dashboard/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/customers/': {
      id: '/_authenticated/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/customers/$id': {
      id: '/_authenticated/dashboard/customers/$id'
      path: '/customers/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/customers/$id/': {
      id: '/_authenticated/dashboard/customers/$id/'
      path: '/'
      fullPath: '/dashboard/customers/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardCustomersIdRoute
    }
    '/_authenticated/dashboard/customers/$id/history': {
      id: '/_authenticated/dashboard/customers/$id/history'
      path: '/history'
      fullPath: '/dashboard/customers/$id/history'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIdHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardCustomersIdRoute
    }
  }
}

interface AuthenticatedDashboardCustomersIdRouteChildren {
  AuthenticatedDashboardCustomersIdHistoryRoute: typeof AuthenticatedDashboardCustomersIdHistoryRoute
  AuthenticatedDashboardCustomersIdIndexRoute: typeof AuthenticatedDashboardCustomersIdIndexRoute
}

const AuthenticatedDashboardCustomersIdRouteChildren: AuthenticatedDashboardCustomersIdRouteChildren =
  {
    AuthenticatedDashboardCustomersIdHistoryRoute:
      AuthenticatedDashboardCustomersIdHistoryRoute,
    AuthenticatedDashboardCustomersIdIndexRoute:
      AuthenticatedDashboardCustomersIdIndexRoute,
  }

const AuthenticatedDashboardCustomersIdRouteWithChildren =
  AuthenticatedDashboardCustomersIdRoute._addFileChildren(
    AuthenticatedDashboardCustomersIdRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCustomersIdRoute: typeof AuthenticatedDashboardCustomersIdRouteWithChildren
  AuthenticatedDashboardCustomersIndexRoute: typeof AuthenticatedDashboardCustomersIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCustomersIdRoute:
      AuthenticatedDashboardCustomersIdRouteWithChildren,
    AuthenticatedDashboardCustomersIndexRoute:
      AuthenticatedDashboardCustomersIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
