name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Validate PR
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Check Types
        run: bun run check-types

      - name: Run Build
        run: bun run build
