name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Validate PR
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the PR
      - name: Checkout Code
        uses: actions/checkout@v4

      # Biome Linting
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci src

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Generate Prisma
        run: npx prisma generate

      - name: Run Build
        run: npm run build