name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Validate PR
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      # Checkout the code from the PR
      - name: Checkout Code
        uses: actions/checkout@v4

      # Biome Linting
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci src

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npx vitest --coverage.enabled true
      - name: Report Coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Generate Prisma
        run: npx prisma generate

      - name: Run Build
        run: npm run build